### ISSUE TITLE
customizable typing module names

### ISSUE THREAD

**Issue by jorenham** [jorenham/unpy#31]
ruff does this as 

```toml
[tool.ruff.lint]
typing-modules = ["airflow.typing_compat"]
```

https://docs.astral.sh/ruff/settings/#lint_typing-modules

by default, it's `["typing", "typing_extensions"]`
